### ISSUE TITLE
"Error parsing the file" when trying to load 3mf files

### ISSUE THREAD

**Issue by AlbertMN** [omrips/viewstl#18]
Hey there. Running the latest version I get the following in the console whenever I try to load a `.3mf` file; `ERROR: Error parsing the file`

I can load `3mf` files on https://www.viewstl.com/ though, so don't really know where it's going wrong. `obj` and `stl` files are loaded just fine. Load them using the following code;

```
stlViewer = new StlViewer(document.getElementById("stl_cont"), {
  allow_drag_and_drop: false,
  auto_rotate: true,
  models: {
    id: 1,
    filename: (url to .3mf, .stl or .obj model),
    rotationx: -90,
    scale: 0.5,
    color: "#29ABE2",
  }
});
```

Any tips?

**Comment by tristanluther28** [comment]
Hi AlbertMN,

3mf and vsb files also require JSZip in order to be parsed correctly. See the [Dependency on JSZip library](https://github.com/omrips/viewstl#dependency-on-jszip-library) section in the README.md

Do you already have JSZip installed?

**Comment by omrips** [comment]
It can be JSZip, but in such case you should also see an error "JSZip is missing".

It can be also server-side problem (as the client gets invalid result from the server).
Are the plugin files and the model files are both on the same server?

**Comment by AlbertMN** [comment]
Same server, same method used when getting obj and stl files.

I don't have the dependency you're talking about, so that could be it, but no error saying that.

**Comment by AlbertMN** [comment]
Adding the JSZip library fixed it - sorry for missing that part, thanks for your help! :)
