### ISSUE TITLE
Scale <1 

### ISSUE THREAD

**Issue by TaskManager91** [omrips/viewstl#5]
hello and thanks for this great simple stl viewer!

Unfortunately the scale does not seem to accept smaller values (e.g. 0.5 to display the object only half as large).

Auto_resize cuts off a bit from my figure, so I want to make it smaller. Even if Auto_resize is set to false, no negative zoom is accepted.

I would appreciate an update here!

**Comment by omrips** [comment]
Sorry for the long delayed answer ...
It is working fine in my tests - can you please post your code here?
